name: ECO5100
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip=21.0.1
  - numpy=1.20.3
  - numpy-base=1.20.3
  - scipy=1.7.1
  - pandas=1.3.2
  - matplotlib=3.4.2
  - statsmodels=0.13.0