wandb_version: 1

learning_rate:
  desc: null
  value: 0.02
architecture:
  desc: null
  value: FNN
dataset:
  desc: null
  value: fashion-mnist
epochs:
  desc: null
  value: 10
_wandb:
  desc: null
  value:
    python_version: 3.10.8
    cli_version: 0.15.11
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1695902890.908433
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.10.8
      5: 0.15.11
      8:
      - 5
      13: linux-x86_64
